medicine/urls.py
from django.urls import path
from .views import MedListView, AddToCartView, CartView, CartUpdateView, CartDeleteView, OrderView, CreateOrder

app_name = 'medicine'

urlpatterns = [
    path('', MedListView.as_view(), name='medicine_list'),
    path('add/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    
    
    path('<int:pk>/edit/', CartUpdateView.as_view(), name='update_cart'),
    path('<int:pk>/delete/', CartDeleteView.as_view(), name='delete_cart'),
    # path('<int:pk>/', CartDetailView.as_view(), name='cart_detail'),
    path('create/', CreateOrder.as_view(), name='checkout'),
    
    path('order/', OrderView.as_view(), name='order'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('news/', include('newss.urls')),
    path('medicine/', include('medicine.urls')),
    path('contact/', include('contact.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Medicine(models.Model):
    name = models.CharField(max_length=150)
    price = models.PositiveIntegerField()
    date_added = models.DateField(auto_now_add=True)
    thumb = models.ImageField(default='p-6', blank=True, null=True)
    quantity = models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.name

class Cart(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    total_price = models.PositiveIntegerField()
    c_quantity = models.PositiveIntegerField(default=0)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.pk) + " "+str(self.username)+" "+str(self.medicine)
    
    def get_absolute_url(self):    
        return reverse('medicine:cart_detail', kwargs={'pk': self.pk})

    def updateCart(self):    
        return reverse('medicine:update_cart', kwargs={'pk': self.pk})
    
    def deleteCart(self):    
        return reverse('medicine:delete_cart', kwargs={'pk': self.pk})


class Order(models.Model):
    username = models.ForeignKey(User, on_delete=models.PROTECT)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,)
    address = models.CharField(max_length=250)
    phone = models.CharField(max_length=12)

    def __str__(self):
        return str(self.pk) + " "+str(self.cart)

medicine/forms.py
from django import forms

QUANTITY_RANGE = [(i,str(i)) for i in range(1,250)]

class AddToCart(forms.Form):
    quantity = forms.TypedChoiceField(choices=QUANTITY_RANGE, coerce=int)


from .models import Order

class CreateOrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ('address', 'phone', 'cart')
        # fields('cart').widget = forms.HiddenInput()
        
        # widgets = {'cart': forms.HiddenInput()}
        

medicine/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin 
)
from django.views.generic import ListView, DetailView, FormView, UpdateView,  DeleteView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from .forms import AddToCart, CreateOrderForm
from .models import Medicine, Cart, Order
from django import forms

class MedListView(ListView):
    model = Medicine
    context_object_name = 'med_list'
    template_name = 'medicine/medicine_list.html'

class CartView(LoginRequiredMixin, ListView):
    model = Cart
    context_object_name = 'cart_list'
    template_name = 'medicine/cart.html'


class AddToCartView(LoginRequiredMixin, DetailView, FormView):
    model = Medicine
    template_name = 'medicine/addcart.html'
    form_class = AddToCart
    success_url = reverse_lazy('medicine:cart')
    
    def form_valid(self, form):
        # Calls the custom send method
        cl = form.cleaned_data
        ob = self.get_object()
        med = Medicine.objects.get(id=ob.id)
        med_ex = Cart.objects.filter(medicine=ob.id, username=self.request.user.id).exists()
        user_ex = Cart.objects.filter(username=self.request.user.id).exists()
        med_data = Cart.objects.filter(medicine=ob.id).values('medicine_id')
        user_data = Cart.objects.filter(username=self.request.user.id).values('medicine_id')
       #med_id_user = user_data[0]['medicine_id']
        #med_id_med = med_data[0]['medicine_id']
        q = cl['quantity']
        p = 0
       
        if med_ex and user_ex:
            k = list(Cart.objects.filter(username=self.request.user.id, medicine=ob.id).values('c_quantity','total_price'))
            q +=  k[0]['c_quantity']
            p = q * med.price
            Cart.objects.filter(username=self.request.user.id, medicine=ob.id).update(c_quantity = q,total_price=p)
        else:
            Cart.objects.create(medicine=med, 
            c_quantity=cl['quantity'], total_price=cl['quantity']*med.price, username=self.request.user)
        

        return redirect("medicine:cart")



class CartUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Cart
    template_name = 'medicine/cart_update.html'
    success_url = reverse_lazy('medicine:cart')
    fields = ('c_quantity',)
    def form_valid(self, form):
        cl = form.cleaned_data
        ob = self.get_object()
        # med = Medicine.objects.get(id=ob.id)
        # cart_ids = Cart.objects.filter(medicine=ob.id).values_list('medicine', flat=True)
        p = int(cl['c_quantity']) * int(ob.medicine.price)
        Cart.objects.filter(id=ob.id).update(
                    c_quantity = cl['c_quantity'],
                    total_price=p
                )
        return redirect("medicine:cart")
    def test_func(self):  
        obj = self.get_object()
        return obj.username == self.request.user


class CartDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Cart
    template_name = 'medicine/cart_delete.html'
    success_url = reverse_lazy('medicine:cart')
    def test_func(self):  
        obj = self.get_object()
        return obj.username == self.request.user

# class CartDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
#     model = Cart
#     template_name = 'medicine/cart_detail.html'
#     def test_func(self):  
#         obj = self.get_object()
#         return obj.username == self.request.user


class OrderView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'medicine/display_orders.html'
    

class CreateOrder(LoginRequiredMixin, CreateView):
    model = Order
    template_name = 'medicine/checkout.html'
    success_url = reverse_lazy("medicine:cart")
    form_class = CreateOrderForm
    def form_valid(self, form):  
        # cl = form.cleaned_data
        # cart = Cart.objects.filter(username=self.request.user.id).values('id')
        form.instance.username = self.request.user
        # cc = Cart.objects.filter(username=self.request.user).get(id=cart)
        
        # form.instance.cart = cart[0]['id']
        return super().form_valid(form)

medicine/templates/medicine/addcart.html
{% extends 'base.html' %}
{% block title %}
<title>Add To Cart</title>
{% endblock title %}
{% block content %}
{%load static%}
<link href="{% static 'css/med.css' %}" rel="stylesheet">
<div class="add_cart" >
<form method="post">{% csrf_token %} {{form}}
    <input type="submit" value="submit"/>
</form>
</div>
{% endblock content %}

medicine/templates/medicine/cart.html
{% extends 'base.html' %} 
{% block title %}
<title>Cart</title>
{% endblock title %}

{% block content %}
{% load static %}
<link href="{% static 'css/med.css' %}" rel="stylesheet" />
{% if cart_list %}
{% for c in cart_list %}
{% if c.username == user %}
<div class="det">
<a href="{% url 'medicine:order' %}">
  My Orders
</a>

<img src="{{c.medicine.thumb.url}}" >
<h4>Name:</h4>{{c.medicine.name}}
<h4>Quantity:</h4>{{c.c_quantity}}
<h4>Price:EGP</h4>{{c.total_price}}
<div class="btn_containe"> 
    <a href="{{ c.updateCart }}">
      Update
    </a>
    <a href="{{ c.deleteCart }}">
        Delete
      </a>
      <a href="{% url 'medicine:checkout' %}">
        CheckOut
      </a>
</div>
</div>
{% endif %}

{% endfor %}
{% endif %}
<div class =" add_cart">
<h3> <a href="{% url 'medicine:medicine_list' %}">
  Go To Shop
</a></h3>
</div>
{% endblock content %}

medicine/templates/medicine/cart_delete.html
{% extends 'base.html' %}
{% block title %}
<title>{{ object.medicine }}</title>
{% endblock title %}

{% block content %}
<h1>Delete {{object.medicine}}</h1>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.medicine }}"?</p>
          <input type="submit" value="Confirm"></form>
{% endblock content %}

medicine/templates/medicine/cart_detail.html
{% extends 'base.html' %}
{% load static %}
<link href="{% static 'css/med.css' %}" rel="stylesheet" />
{% block title %}
<title>{{ object.medicine.name }}</title>
{% endblock title %}
{% block content %}
<div class="det">

  <img src="{{object.medicine.thumb.url}}" >
  <h4>Name:</h4>{{object.medicine.name}}
  <h4>Quantity:</h4>{{object.c_quantity}}
  <h4>Price:EGP</h4>{{object.total_price}}

  <div class="btn_container"> 
      <a href="{{ object.updateCart }}">
        Update
      </a>
      <a href="{{ object.deleteCart }}">
          Delete
        </a>
        <a href="{% url 'medicine:checkout' %}">
          CheckOut
        </a>

  </div>
</div>      
{% endblock content %}

medicine/templates/medicine/cart_update.html
{% extends 'base.html' %} {% block title %}
<title>{{ object.medicine}}</title>
{% endblock title %} {% load crispy_forms_tags %} {% block content %}

<form
  class="mx-auto my-4 text-center"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{ form | crispy }}
  <div class="d-flex justify-content-center">
    <input class="btn btn-success my-3" type="submit" value="Update" />
  </div>
</form>
{% endblock content %}

medicine/templates/medicine/checkout.html
{% extends 'base.html' %} 
{% block title %}
<title>CheckOut</title>
{% endblock title %}
{% load crispy_forms_tags %} 
{%load static%}
<link href="{% static 'css/med.css' %}" rel="stylesheet" />
{% block content %}
<form method="post">{% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

medicine/templates/medicine/display_orders.html
{% extends 'base.html' %} 
{% block title %}
<title>Orders</title>
{% endblock title %}

{% block content %}
{%load static}
<link href="{% static 'css/med.css' %}" rel="stylesheet" />

{% block content %}

{% if order_list %}
{% for order in order_list %}
{% if user == order.username %}
<div class="del" style="margin-left: 40%;">
    <img src="{{ order.cart.medicine.thumb.url }}" >


    <p> Name: {{ order.cart.medicine }}</p>
    <p>Total_Price: {{ order.cart.total_price }}</p>
    <p>Quantity: {{ order.cart.c_quantity }}</p>
    <p>Address: {{ order.address }}</p>
    <p>Phone: {{ order.phone }}</p>
  </div>
{% endif %}    
{% endfor %}
{% else %}
<h4>No Orders</h4>
<h3> <a href="{% url 'medicine:medicine_list' %}">
    Go To Shop
  </a></h3>
{% endif %}

{% endblock content %}

medicine/templates/medicine/medicine_list.html
{% extends 'base.html' %}
{% block title %}
<title>Medicine</title>
{% endblock title %}


{% block content %}
{% load static %}
<link href="{% static 'css/med.css' %}" rel="stylesheet" />
<div class="medicines_list" >
  <section class="health_section layout_padding">
      <div class="health_carousel-container">
        <h2 class="text-uppercase">
          Medicines
        </h2>
        <div class="carousel-wrap layout_padding2">
        <div >
            <div class="item">
              {% if med_list %}
                  {% for med in med_list %}
                  <div class="img-box">
                    <img src="{{ med.thumb.url }}" alt="">
                  </div>
                  {% if med.quantity %}
                <div class="btn_container"> 
                  <a href="{% url 'medicine:add_to_cart' med.id %}">
                    Buy Now
                  </a>
                </div>
                <div class="detail-box">
                  <div class="star_container">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>

                  </div>
                  
                  <div class="text">

                    <h6>
                      {{ med.name }}
                    </h6>
                    <h6 class="price">
                      <span style="color:black">
                        Price:
                      </span>
                      {{ med.price }}EGP
                    </h6>
                    {% else %}
                    <h6>Not Available</h6>
                    {% endif %}
                  </div>
                </div>
              
                {% endfor %}
            </div>
              {% else %}
              <h3>No Medicines</h3>
              {% endif %}
            </div>
          </div>
      </div>
    </div>
  </div>
    
  </section>
</div>

{% endblock content %}