newss/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView, NewsUpdateView, NewsDeleteView, NewsCreateView

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news_list'),
    path('create/', NewsCreateView.as_view(), name='news_create'),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('<int:pk>/update/', NewsUpdateView.as_view(), name='news_update'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('news/', include('newss.urls')),
    path('medicine/', include('medicine.urls')),
    path('contact/', include('contact.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newss/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class News(models.Model):
    username= models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=80)
    body = models.TextField()
    thumb = models.ImageField(blank=True, null=True, default='about-medicine.png')


    def __str__(self):
        return self.title

    def snip(self):
        return self.body[:150]

    def get_absolute_url(self):
        return reverse('news:news_detail', kwargs={'pk':self.pk})

    def delete_news(self):
        return reverse('news:news_delete', kwargs={'pk':self.pk})        

    def update_news(self):
        return reverse('news:news_update', kwargs={'pk':self.pk})  

newss/forms.py
from django.forms import ModelForm
from .models import News



class UpdateForm(ModelForm):
    class Meta:
        model = News
        fields = ('title', 'body', 'thumb')

newss/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin 
)
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from .models import News
from .forms import UpdateForm

class NewsListView(ListView):
    model = News
    template_name = 'news/news_list.html'


class NewsCreateView(LoginRequiredMixin, CreateView):
    model = News
    success_url = reverse_lazy('news:news_list')
    fields = ('title', 'body', 'thumb')
    template_name = 'news/news_create.html'
    def form_valid(self, form):  
        form.instance.username = self.request.user
        return super().form_valid(form)

class NewsDetailView(LoginRequiredMixin, DetailView):
    model = News
    template_name = 'news/news_detail.html'


class NewsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = News
    form_class = UpdateForm
    template_name = 'news/news_update.html'
    success_url = reverse_lazy('news:news_list')
    def test_func(self):  # new
        obj = self.get_object()
        return obj.username == self.request.user


    

class NewsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = News
    template_name = 'news/news_delete.html'
    success_url = reverse_lazy('news:news_list')
    def test_func(self):  
        obj = self.get_object()
        return obj.username == self.request.user

newss/templates/news/news_create.html
{% extends 'base.html' %} {% block title %}
<title>Post News</title>
{% endblock title %} {% load crispy_forms_tags %} {% block content %}

<div class="mx-auto my-4 text-center">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form | crispy }}
    <div class="mx-auto my-4 text-center">
      <div class="d-flex justify-content-center">
        <input class="btn btn-success my-3" type="submit" value="Submit" />
      </div>
    </div>
  </form>
</div>
{% endblock content %}

newss/templates/news/news_delete.html
{% extends 'base.html' %}
{% block title %}
<title>{{ object.title }}</title>
{% endblock title %}

{% block content %}
<h1>Delete {{object.title}}</h1>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.title }}"?</p>
          <input type="submit" value="Confirm"></form>
{% endblock content %}

newss/templates/news/news_detail.html
{% extends 'base.html' %}
{% block title %}
<title>{{ object.title }}</title>
{% endblock title %}

{% block content %}
<section class="about_section layout_padding">
    <div class="container">
      <div class="custom_heading-container ">
        <h2>
            {{ object.title }}
        </h2>
      </div>
     
      <div class="img-box">
        {% if news.thumb %}
        <img src="{{ news.thumb.url }}" alt="">
        {% else %}
        <h3>No Image</h3>
        {% endif %}
      </div>
      <div class="detail-box">
            
            <p>
            {{ object.body}}
            </p>
            {% if object.username == user %}
            <div class="d-flex justify-content-center">
                <a href="{{ object.update_news }}">
                  Edit
                </a>
              </div>
              <div class="d-flex justify-content-center">
                <a href="{{ object.delete_news }}">
                  Delete
                </a>
              </div>
              {% endif %}
      </div>
      

    </div>
  </section>

{% endblock content %}

newss/templates/news/news_list.html
{% extends 'base.html' %}
{% block title %}
<title>News</title>
{% endblock title %}




{% block content %}
<section class="about_section layout_padding">
    <div class="container">
      <div class="custom_heading-container ">
        <h2>
          News
        </h2>
      </div>
      <div class="detail-box">
        <div class="d-flex justify-content-center">
          <a href="{% url 'news:news_create' %}">
            Create
          </a>
        </div>
    </div>
      {% if news_list %}
      {% for news in news_list %}
      <div class="img-box">
        <h3>Created By:{{ news.username }}</h3>
            <br>
        {% if news.thumb %}
        <img src="{{ news.thumb.url }}" alt="">
        {% else %}
        <h3>No Image</h3>
        {% endif %}
      </div>
      <div class="detail-box">
        <h3>{{ news.title }}</h3>
        <p>
          {{ news.snip }}
        </p>
        <div class="d-flex justify-content-center">
          <a href="{{ news.get_absolute_url }}">
            Read More
          </a>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <p>No News For Now</p>
      {% endif %}
    </div>
  </section>

{% endblock content %}

newss/templates/news/news_update.html
{% extends 'base.html' %} {% block title %}
<title>{{ object.title }}</title>
{% endblock title %} {% load crispy_forms_tags %} {% block content %}

<form
  class="mx-auto my-4 text-center"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{ form | crispy }}
  <div class="d-flex justify-content-center">
    <input class="btn btn-success my-3" type="submit" value="Update" />
  </div>
</form>
{% endblock content %}