accounts/urls.py
from django.urls import path
from .views import SignUpView, ProfileView
app_name = 'accounts'


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

contact/urls.py
from django.urls import path
from .views import ContactView, SuccessView, FailedView
app_name = 'contact'


urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
    path('success/', SuccessView.as_view(), name='success'),
    path('failed/', FailedView.as_view(), name='failed'),
]

newss/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView, NewsUpdateView, NewsDeleteView, NewsCreateView

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news_list'),
    path('create/', NewsCreateView.as_view(), name='news_create'),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('<int:pk>/update/', NewsUpdateView.as_view(), name='news_update'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
]

pages/urls.py
from django.urls import path
from .views import AboutPageView,HomePageView


app_name = 'pages'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('news/', include('newss.urls')),
    path('medicine/', include('medicine.urls')),
    path('contact/', include('contact.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load crispy_forms_tags %} 
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  {% block title %}<title>Medion</title>{% endblock title %}

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700|Roboto:400,700&display=swap" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />


</head>

<body>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <div class="top_contact-container">
          <div class="tel_container">
            <a href="">
              <img src="{% static 'images/telephone-symbol-button.png' %}" alt=""> Call : +201022352842
            </a>
          </div>
          <div class="social-container">
            <a href="">
              <img src="{% static 'images/fb.png' %}" alt="" class="s-1">
            </a>
            <a href="">
              <img src="{% static 'images/twitter.png' %}" alt="" class="s-2">
            </a>
            <a href="">
              <img src="{% static 'images/instagram.png' %}" alt="" class="s-3">
            </a>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
          <a class="navbar-brand" href="{% url 'pages:home' %}">
            <img src="{% static 'images/logo.png' %}" alt="">
            <span>
              Medion
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex  flex-column flex-lg-row align-items-center w-100 justify-content-between">
              <ul class="navbar-nav  ">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:about' %}"> About </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'medicine:medicine_list' %}"> Medicine </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'medicine:cart' %}"> Cart </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'news:news_list' %}"> News </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact:contact' %}">Contact us</a>
                </li>
              </ul>
              
              <div class="login_btn-contanier ml-0 ml-lg-5">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><span>Logout</span></a>
                <a style="color: white;"><span>{{user}}</span></a>
                <a href="{% url 'accounts:profile' %}"> <img  src="{% static 'images/user.png' %}" alt=""></a>
                {% else %}
                <a href="{% url 'login' %}"><span>Login</span></a>
                {% endif %}
                  
                </a>
              </div>
            </div>
          </div>

        </nav>
      </div>
    </header>
    <!-- end header section -->

    {% block content %}
    {% endblock content %}


  <!-- info section -->
  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h4>
              Contact
            </h4>
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/telephone-symbol-button.png' %}" alt="">
              </div>
              <div class="detail-box">
                <h6>
                  +201022352842
                </h6>
              </div>
            </div>
            <div class="box">
              <div class="img-box">
                <img src="{% static 'images/email.png' %}" alt="">
              </div>
              <div class="detail-box">
                <h6>
                  anasosama914@gmail.com
                </h6>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_menu">
            <h4>
              Menu
            </h4>
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:about' %}"> About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'medicine:medicine_list' %}"> Medicine </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'medicine:cart' %}"> Cart </a>
              </li>
            </ul>
          </div>
        </div>
        
      </div>
    </div>
  </section>


  <!-- end info section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js">
  </script>
  <script type="text/javascript">
    $(".owl-carousel").owlCarousel({
      loop: true,
      margin: 10,
      nav: true,
      navText: [],
      autoplay: true,
      responsive: {
        0: {
          items: 1
        },
        600: {
          items: 2
        },
        1000: {
          items: 4
        }
      }
    });
  </script>
  <script type="text/javascript">
    $(".owl-2").owlCarousel({
      loop: true,
      margin: 10,
      nav: true,
      navText: [],
      autoplay: true,

      responsive: {
        0: {
          items: 1
        },
        600: {
          items: 2
        },
        1000: {
          items: 4
        }
      }
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous">
</script>
</body>

</html>